/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arqsis.aop2.view.clientes;

import arqsis.aop2.controller.ClientesController;
import arqsis.aop2.model.Cliente;
import java.awt.Point;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author freit
 */
public class Consulta extends javax.swing.JInternalFrame {

    private final JDesktopPane jdpPrincipal;
    private final DefaultTableModel model;
    private final ClientesController controller;
    /**
     * Creates new form Consulta
     */
    
    public Consulta(JDesktopPane jdpPrincipal) {
        initComponents();
        this.model = (DefaultTableModel) gridClientes.getModel();
        model.setNumRows(0);
        this.jdpPrincipal = jdpPrincipal;
        this.controller = new ClientesController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPesquisaNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridClientes = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Clientes");

        jLabel1.setText("Nome:");

        gridClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome", "Sobrenome", "E-mail", "Data de Nascimento", "CPF", "Idade", "Profissao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gridClientesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(gridClientes);
        if (gridClientes.getColumnModel().getColumnCount() > 0) {
            gridClientes.getColumnModel().getColumn(0).setHeaderValue("Matrícula");
            gridClientes.getColumnModel().getColumn(1).setHeaderValue("Nome");
            gridClientes.getColumnModel().getColumn(2).setHeaderValue("Sobrenome");
            gridClientes.getColumnModel().getColumn(3).setHeaderValue("E-mail");
            gridClientes.getColumnModel().getColumn(4).setHeaderValue("Data de Nascimento");
            gridClientes.getColumnModel().getColumn(5).setHeaderValue("CPF");
            gridClientes.getColumnModel().getColumn(6).setHeaderValue("Idade");
            gridClientes.getColumnModel().getColumn(7).setHeaderValue("Profissao");
        }

        btnPesquisar.setText("Buscar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnNovo)
                    .addComponent(btnExcluir))
                .addGap(18, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        Formulario frm = new Formulario();
        this.jdpPrincipal.add(frm);
        frm.setVisible(true);
        this.updateGrid(controller.findByName(this.txtPesquisaNome.getText()));
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        this.updateGrid(controller.findByName(this.txtPesquisaNome.getText()));
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void gridClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridClientesMousePressed
        // TODO add your handling code here:
        JTable table =(JTable) evt.getSource();
        Point point = evt.getPoint();
        int row = table.rowAtPoint(point);
        
        if (evt.getClickCount() == 2 && table.getSelectedRow() != -1) {
            Formulario frm = new Formulario((int) model.getValueAt(row, 0));
            this.jdpPrincipal.add(frm);
            frm.setVisible(true);
        }
    }//GEN-LAST:event_gridClientesMousePressed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (gridClientes.getSelectedRow() != -1) {
            this.controller.delete((int) model.getValueAt(gridClientes.getSelectedRow(), 0));
            this.updateGrid(controller.findByName(this.txtPesquisaNome.getText()));
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    private void updateGrid(List<Cliente> clientes) {
        model.setNumRows(0);
        for (Cliente cliente : clientes) {
            this.model.addRow(new Object[] {
                cliente.getMatricula(),
                cliente.getNome(),
                cliente.getSobreNome(),
                cliente.getEmail(),
                cliente.getDataDeNascimento(),
                cliente.getCpf(),
                cliente.getIdade(),
                cliente.getProfissao()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JTable gridClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPesquisaNome;
    // End of variables declaration//GEN-END:variables
}
